-- 学校情報管理テーブル
CREATE TABLE SCHOOL (
    CD CHAR(3) PRIMARY KEY NOT NULL,
    NAME VARCHAR(20) DEFAULT NULL
);

-- 学校別クラス情報管理テーブル
CREATE TABLE CLASS_NUM (
    SCHOOL_CD CHAR(3) NOT NULL,
    CLASS_NUM VARCHAR(5) NOT NULL,
    PRIMARY KEY (SCHOOL_CD, CLASS_NUM),
    FOREIGN KEY (SCHOOL_CD) REFERENCES SCHOOL(CD)
);

-- 学生情報管理テーブル
CREATE TABLE STUDENT (
    NO VARCHAR(10) PRIMARY KEY NOT NULL,
    NAME VARCHAR(10) DEFAULT NULL,
    ENT_YEAR INTEGER DEFAULT NULL,
    CLASS_NUM CHAR(3) DEFAULT NULL,
    IS_ATTEND BOOLEAN DEFAULT NULL,
    SCHOOL_CD CHAR(3) DEFAULT NULL,
    FOREIGN KEY (SCHOOL_CD, CLASS_NUM) REFERENCES CLASS_NUM(SCHOOL_CD, CLASS_NUM)
);

-- 科目情報管理テーブル
CREATE TABLE SUBJECT (
    SCHOOL_CD CHAR(3) NOT NULL,
    CD CHAR(3) NOT NULL,
    NAME VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (SCHOOL_CD, CD),
    FOREIGN KEY (SCHOOL_CD) REFERENCES SCHOOL(CD)
);

-- 教員情報管理テーブル
CREATE TABLE TEACHER (
    ID VARCHAR(10) PRIMARY KEY NOT NULL,
    PASSWORD VARCHAR(30) DEFAULT NULL,
    NAME VARCHAR(10) DEFAULT NULL,
    SCHOOL_CD CHAR(3) DEFAULT NULL,
    FOREIGN KEY (SCHOOL_CD) REFERENCES SCHOOL(CD)
);

-- 学生別得点情報管理テーブル
CREATE TABLE TEST (
    STUDENT_NO VARCHAR(10) NOT NULL,
    SUBJECT_CD CHAR(3) NOT NULL,
    SCHOOL_CD CHAR(10) NOT NULL,
    NO INTEGER NOT NULL,
    POINT INTEGER DEFAULT NULL,
    CLASS_NUM VARCHAR(5) DEFAULT NULL,
    PRIMARY KEY (STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO),
    FOREIGN KEY (STUDENT_NO) REFERENCES STUDENT(NO),
    FOREIGN KEY (SCHOOL_CD) REFERENCES SCHOOL(CD),
    FOREIGN KEY (SUBJECT_CD) REFERENCES SUBJECT(CD)
);