INSERT INTO SCHOOL (CD, NAME) VALUES
('oom', '131');

INSERT INTO CLASS_NUM (SCHOOL_CD, CLASS_NUM) VALUES
('oom', '131');

INSERT INTO STUDENT (NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD) VALUES
('2231111', '大原太郎', 2023, '131', TRUE, 'oom');

INSERT INTO SUBJECT (SCHOOL_CD, CD, NAME) VALUES
('oom', 'A02', '国語');

INSERT INTO TEACHER (ID, PASSWORD, NAME, SCHOOL_CD) VALUES
('admin', 'password', '大原花子', 'oom');

INSERT INTO TEST (STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM) VALUES
('2231111', 'A02', 'oom', 1, 100, '131');