;             
CREATE USER IF NOT EXISTS SA SALT '03c073b77516164b' HASH '53ef87c852ea4ffd716ca32ffee46ad7df153d3157b6aa75becd916b465328c8' ADMIN;           
CREATE CACHED TABLE PUBLIC.SCHOOL(
    CD CHAR(3) NOT NULL,
    NAME VARCHAR(20) DEFAULT NULL
);           
ALTER TABLE PUBLIC.SCHOOL ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(CD); 
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.SCHOOL;  
INSERT INTO PUBLIC.SCHOOL(CD, NAME) VALUES
('oom', '131');   
CREATE CACHED TABLE PUBLIC.CLASS_NUM(
    SCHOOL_CD CHAR(3) NOT NULL,
    CLASS_NUM VARCHAR(5) NOT NULL
); 
ALTER TABLE PUBLIC.CLASS_NUM ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(SCHOOL_CD, CLASS_NUM);            
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.CLASS_NUM;               
INSERT INTO PUBLIC.CLASS_NUM(SCHOOL_CD, CLASS_NUM) VALUES
('oom', '131');    
CREATE CACHED TABLE PUBLIC.STUDENT(
    NO VARCHAR(10) NOT NULL,
    NAME VARCHAR(10) DEFAULT NULL,
    ENT_YEAR INTEGER DEFAULT NULL,
    CLASS_NUM CHAR(3) DEFAULT NULL,
    IS_ATTEND BOOLEAN DEFAULT NULL,
    SCHOOL_CD CHAR(3) DEFAULT NULL
);   
ALTER TABLE PUBLIC.STUDENT ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(NO);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.STUDENT; 
INSERT INTO PUBLIC.STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD) VALUES
('2231111', STRINGDECODE('\u5927\u539f\u592a\u90ce'), 2023, '131', TRUE, 'oom');      
CREATE CACHED TABLE PUBLIC.SUBJECT(
    SCHOOL_CD CHAR(3) NOT NULL,
    CD CHAR(3) NOT NULL,
    NAME VARCHAR(20) DEFAULT NULL
);         
ALTER TABLE PUBLIC.SUBJECT ADD CONSTRAINT PUBLIC.CONSTRAINT_BB PRIMARY KEY(SCHOOL_CD, CD);    
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.SUBJECT; 
INSERT INTO PUBLIC.SUBJECT(SCHOOL_CD, CD, NAME) VALUES
('oom', 'A02', STRINGDECODE('\u56fd\u8a9e'));         
CREATE CACHED TABLE PUBLIC.TEACHER(
    ID VARCHAR(10) NOT NULL,
    PASSWORD VARCHAR(30) DEFAULT NULL,
    NAME VARCHAR(10) DEFAULT NULL,
    SCHOOL_CD CHAR(3) DEFAULT NULL
);         
ALTER TABLE PUBLIC.TEACHER ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TEACHER; 
INSERT INTO PUBLIC.TEACHER(ID, PASSWORD, NAME, SCHOOL_CD) VALUES
('admin', 'password', STRINGDECODE('\u5927\u539f\u82b1\u5b50'), 'oom');     
CREATE CACHED TABLE PUBLIC.TEST(
    STUDENT_NO VARCHAR(10) NOT NULL,
    SUBJECT_CD CHAR(3) NOT NULL,
    SCHOOL_CD CHAR(10) NOT NULL,
    NO INTEGER NOT NULL,
    POINT INTEGER DEFAULT NULL,
    CLASS_NUM VARCHAR(5) DEFAULT NULL
);              
ALTER TABLE PUBLIC.TEST ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TEST;    
INSERT INTO PUBLIC.TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM) VALUES
('2231111', 'A02', 'oom', 1, 100, '131');            
ALTER TABLE PUBLIC.STUDENT ADD CONSTRAINT PUBLIC.CONSTRAINT_BA FOREIGN KEY(SCHOOL_CD, CLASS_NUM) REFERENCES PUBLIC.CLASS_NUM(SCHOOL_CD, CLASS_NUM) NOCHECK;   
ALTER TABLE PUBLIC.SUBJECT ADD CONSTRAINT PUBLIC.CONSTRAINT_BB7 FOREIGN KEY(SCHOOL_CD) REFERENCES PUBLIC.SCHOOL(CD) NOCHECK;  
ALTER TABLE PUBLIC.TEST ADD CONSTRAINT PUBLIC.CONSTRAINT_27 FOREIGN KEY(STUDENT_NO) REFERENCES PUBLIC.STUDENT(NO) NOCHECK;    
ALTER TABLE PUBLIC.TEST ADD CONSTRAINT PUBLIC.CONSTRAINT_273C FOREIGN KEY(SUBJECT_CD) REFERENCES PUBLIC.SUBJECT(CD) NOCHECK;  
ALTER TABLE PUBLIC.TEST ADD CONSTRAINT PUBLIC.CONSTRAINT_273 FOREIGN KEY(SCHOOL_CD) REFERENCES PUBLIC.SCHOOL(CD) NOCHECK;     
ALTER TABLE PUBLIC.TEACHER ADD CONSTRAINT PUBLIC.CONSTRAINT_D4 FOREIGN KEY(SCHOOL_CD) REFERENCES PUBLIC.SCHOOL(CD) NOCHECK;   
ALTER TABLE PUBLIC.CLASS_NUM ADD CONSTRAINT PUBLIC.CONSTRAINT_A5 FOREIGN KEY(SCHOOL_CD) REFERENCES PUBLIC.SCHOOL(CD) NOCHECK; 
